service: top-products-aws-web-scraper-api
frameworkVersion: '3'

provider:
  name: aws
  runtime: nodejs16.x

functions:
  api:
    handler: index.handler
    layers:
      - 'arn:aws:lambda:us-east-1:085485918211:layer:chromiumLayer:1'
    events:
      - httpApi:
          path: /
          method: get

# Esta parte precisa ser adaptada futuramente para a funcionalidade de exportação dos dados do scraper para o DynamoDB.
resources:
  Resources:
    CustomerTable:
      Type: AWS::DynamoDB::Table
      Properties:
        AttributeDefinitions:
          - AttributeName: primary_key
            AttributeType: S
        BillingMode: PAY_PER_REQUEST
        KeySchema:
          - AttributeName: primary_key
            KeyType: HASH
        TableName: ${self:service}-customerTable-${sls:stage}
