service: top-products-aws-web-scraper-api
frameworkVersion: '3'

provider:
  name: aws
  runtime: nodejs16.x

functions:
  api:
    handler: index.handler
    layers:
      - 'arn:aws:lambda:us-east-1:085485918211:layer:chromiumLayer:1'
    events:
      - httpApi:
          path: /
          method: get

resources:
  Resources:
    DataTable:
      Type: AWS::DynamoDB::Table
      Properties:
        AttributeDefinitions:
          - AttributeName: products_list
            AttributeType: S
        BillingMode: PAY_PER_REQUEST
        KeySchema:
          - AttributeName: products_list
            KeyType: HASH
        TableName: ${self:service}-dataTable

provider:
  environment:
    DYNAMODB_DATA_TABLE: ${self:service}-dataTable